/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List issues in the authenticated workspace */
    get: operations["listIssues"];
    put?: never;
    /** Create an issue */
    post: operations["createIssue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: operations["getIssue"];
    put?: never;
    post?: never;
    delete: operations["deleteIssue"];
    options?: never;
    head?: never;
    patch: operations["updateIssue"];
    trace?: never;
  };
  "/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List visible teams in the authenticated workspace */
    get: operations["listTeams"];
    put?: never;
    /** Create a team with default workflow states */
    post: operations["createTeam"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspaces for the authenticated principal */
    get: operations["listWorkspaces"];
    put?: never;
    /** Create a workspace with a default team and workflow states */
    post: operations["createWorkspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentWorkspace"];
    put?: never;
    post?: never;
    delete: operations["deleteCurrentWorkspace"];
    options?: never;
    head?: never;
    patch: operations["updateCurrentWorkspace"];
    trace?: never;
  };
  "/workspaces/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listWorkspaceMembers"];
    put?: never;
    post: operations["resendWorkspaceInvitation"];
    delete: operations["removeWorkspaceMemberOrInvitation"];
    options?: never;
    head?: never;
    patch: operations["updateWorkspaceMemberOrInvitation"];
    trace?: never;
  };
  "/workspaces/invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["inviteWorkspaceMembers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open a workspace sync WebSocket and replay operations after a version */
    get: operations["watchSync"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      detail?: string;
    };
    Team: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      icon?: string | null;
      isPrivate: boolean;
      issueCount: number;
      memberCount: number;
      currentUserIsMember: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      retiredAt?: string | null;
    };
    TeamListResponse: {
      /** Format: uuid */
      workspaceId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canManageTeams: boolean;
      teams: components["schemas"]["Team"][];
    };
    CreateTeamRequest: {
      name: string;
      key?: string;
      isPrivate?: boolean;
      icon?: string;
    };
    CreateTeamResponse: {
      team: components["schemas"]["Team"];
    };
    /** @enum {string} */
    WorkspaceRole: "owner" | "admin" | "member" | "guest";
    WorkspaceMembership: {
      /** Format: uuid */
      workspaceId: string;
      role: components["schemas"]["WorkspaceRole"];
      workspaceName: string;
      workspaceSlug: string;
    };
    Workspace: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      logo?: string | null;
      region: string;
      fiscalMonth: string;
      welcomeMessage: string;
      plan: string;
    };
    WorkspaceSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TeamSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      /** Format: uuid */
      workspaceId: string;
    };
    CreateWorkspaceRequest: {
      name: string;
      urlSlug: string;
    };
    CreateWorkspaceResponse: {
      workspace: components["schemas"]["WorkspaceSummary"];
      team: components["schemas"]["TeamSummary"];
    };
    CurrentWorkspaceResponse: {
      workspace: components["schemas"]["Workspace"];
    };
    UpdateWorkspaceRequest: {
      name?: string;
      urlSlug?: string;
      logo?: string | null;
      fiscalMonth?: string;
      welcomeMessage?: string;
    };
    WorkspaceMember: {
      id: string;
      /** @enum {string} */
      kind: "member" | "invitation";
      userId?: string | null;
      name: string;
      email: string;
      image?: string | null;
      role: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      status: "active" | "pending";
      teams: string[];
      /** Format: date-time */
      joinedAt: string;
      /** Format: date-time */
      lastSeenAt?: string | null;
      pronouns?: string;
      title?: string;
      location?: string;
      timezone?: string;
      showLocalTime?: boolean;
    };
    WorkspaceMembersResponse: {
      /** Format: uuid */
      workspaceId: string;
      currentUserId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canInviteMembers: boolean;
      members: components["schemas"]["WorkspaceMember"][];
    };
    MutateWorkspaceMemberRequest: {
      /** @enum {string} */
      kind: "member" | "invitation";
      id: string;
      role?: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      action?: "resend";
    };
    InviteWorkspaceMembersRequest: {
      /** Format: uuid */
      workspaceId?: string;
      invites: {
        /** Format: email */
        email: string;
        /** @enum {string} */
        role: "admin" | "member" | "guest";
      }[];
    };
    InviteResult: {
      email: string;
      /** @enum {string} */
      status: "sent" | "failed";
      error?: string;
    };
    InviteWorkspaceMembersResponse: {
      results: components["schemas"]["InviteResult"][];
    };
    SuccessResponse: {
      success: boolean;
    };
    /** @enum {string} */
    IssuePriority: "none" | "urgent" | "high" | "medium" | "low";
    Issue: {
      /** Format: uuid */
      id: string;
      number: number;
      identifier: string;
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id: string;
      assignee_id?: string | null;
      creator_id: string;
      priority: components["schemas"]["IssuePriority"];
      estimate?: number | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: date-time */
      due_date?: string | null;
      sort_order?: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      archived_at?: string | null;
      /** Format: date-time */
      canceled_at?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
    };
    IssueListResponse: {
      data: components["schemas"]["Issue"][];
      next_cursor?: string | null;
    };
    CreateIssueRequest: {
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id?: string | null;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
    };
    UpdateIssueRequest: {
      title?: string;
      description?: string | null;
      /** Format: uuid */
      state_id?: string;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
      sort_order?: number;
      archive?: boolean;
    };
  };
  responses: {
    /** @description RFC 7807 problem response */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    Cursor: string;
    Limit: number;
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listIssues: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        team_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issues page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIssueRequest"];
      };
    };
    responses: {
      /** @description Created issue */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIssueRequest"];
      };
    };
    responses: {
      /** @description Updated issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listTeams: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Teams */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createTeam: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamRequest"];
      };
    };
    responses: {
      /** @description Created team */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTeamResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace memberships */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembership"][];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Created workspace */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            redirectTo: string;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Updated current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active members and pending invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  resendWorkspaceInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Resent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  removeWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  inviteWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteWorkspaceMembersRequest"];
      };
    };
    responses: {
      /** @description Invite results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteWorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  watchSync: {
    parameters: {
      query?: {
        version?: number;
        /** @description Browser/CLI WebSocket auth fallback when Authorization headers are unavailable. */
        access_token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol switch */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
}
