/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List issues in the authenticated workspace */
    get: operations["listIssues"];
    put?: never;
    /** Create an issue */
    post: operations["createIssue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: operations["getIssue"];
    put?: never;
    post?: never;
    delete: operations["deleteIssue"];
    options?: never;
    head?: never;
    patch: operations["updateIssue"];
    trace?: never;
  };
  "/issues/{id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createIssueComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}/reactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["toggleIssueReaction"];
    delete: operations["deleteIssueReaction"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/comments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    patch: operations["updateComment"];
    trace?: never;
  };
  "/comments/{id}/reactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["toggleCommentReaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listLabels"];
    put?: never;
    post: operations["createLabel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/labels/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteLabel"];
    options?: never;
    head?: never;
    patch: operations["updateLabel"];
    trace?: never;
  };
  "/project-labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listProjectLabels"];
    put?: never;
    post: operations["createProjectLabel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project-labels/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteProjectLabel"];
    options?: never;
    head?: never;
    patch: operations["updateProjectLabel"];
    trace?: never;
  };
  "/personal-access-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPersonalAccessTokens"];
    put?: never;
    post: operations["createPersonalAccessToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/personal-access-tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revokePersonalAccessToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects in the authenticated workspace */
    get: operations["listProjects"];
    put?: never;
    /** Create a project */
    post: operations["createProject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    get: operations["getProject"];
    put?: never;
    post?: never;
    delete: operations["deleteProject"];
    options?: never;
    head?: never;
    patch: operations["updateProject"];
    trace?: never;
  };
  "/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List visible teams in the authenticated workspace */
    get: operations["listTeams"];
    put?: never;
    /** Create a team with default workflow states */
    post: operations["createTeam"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/teams/{key}/cycles": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    get: operations["listTeamCycles"];
    put?: never;
    post: operations["createTeamCycle"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/teams/{key}/cycles/{cycle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteTeamCycle"];
    options?: never;
    head?: never;
    patch: operations["updateTeamCycle"];
    trace?: never;
  };
  "/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspaces for the authenticated principal */
    get: operations["listWorkspaces"];
    put?: never;
    /** Create a workspace with a default team and workflow states */
    post: operations["createWorkspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentWorkspace"];
    put?: never;
    post?: never;
    delete: operations["deleteCurrentWorkspace"];
    options?: never;
    head?: never;
    patch: operations["updateCurrentWorkspace"];
    trace?: never;
  };
  "/workspaces/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listWorkspaceMembers"];
    put?: never;
    post: operations["resendWorkspaceInvitation"];
    delete: operations["removeWorkspaceMemberOrInvitation"];
    options?: never;
    head?: never;
    patch: operations["updateWorkspaceMemberOrInvitation"];
    trace?: never;
  };
  "/workspaces/invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["inviteWorkspaceMembers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open a workspace sync WebSocket and replay operations after a version */
    get: operations["watchSync"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      detail?: string;
    };
    CommentUser: {
      name: string;
      image?: string | null;
    };
    ReactionSummary: {
      emoji: string;
      count: number;
      reacted?: boolean;
      reactedByMe?: boolean;
    };
    ReactionSummaryList: components["schemas"]["ReactionSummary"][];
    Comment: {
      /** Format: uuid */
      id: string;
      body: string;
      /** Format: uuid */
      issue_id: string;
      user_id: string;
      user: components["schemas"]["CommentUser"];
      owned_by_me: boolean;
      can_edit: boolean;
      can_delete: boolean;
      reactions: components["schemas"]["ReactionSummary"][];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateCommentRequest: {
      body: string;
    };
    UpdateCommentRequest: {
      body: string;
    };
    ReactionRequest: {
      emoji: string;
    };
    Label: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
      teamName?: string | null;
      teamKey?: string | null;
      /** @enum {string} */
      scope: "workspace" | "team";
      /** Format: date-time */
      archivedAt?: string | null;
      issueCount: number;
      /** Format: date-time */
      lastApplied?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LabelListResponse: {
      labels: components["schemas"]["Label"][];
    };
    LabelResponse: {
      label: components["schemas"]["Label"];
    };
    CreateLabelRequest: {
      name: string;
      color?: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
    };
    UpdateLabelRequest: {
      name?: string;
      color?: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
      archived?: boolean;
      convertToGroup?: boolean;
    };
    ProjectLabel: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      description?: string | null;
      projectCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ProjectLabelListResponse: {
      labels: components["schemas"]["ProjectLabel"][];
    };
    ProjectLabelResponse: {
      label: components["schemas"]["ProjectLabel"];
    };
    CreateProjectLabelRequest: {
      name: string;
      color?: string;
      description?: string | null;
    };
    UpdateProjectLabelRequest: {
      name?: string;
      color?: string;
      description?: string | null;
    };
    PersonalAccessToken: {
      /** Format: uuid */
      id: string;
      name: string;
      token_prefix: string;
      scopes: string[];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: date-time */
      revoked_at?: string | null;
    };
    PersonalAccessTokenListResponse: {
      tokens: components["schemas"]["PersonalAccessToken"][];
    };
    CreatePersonalAccessTokenRequest: {
      name: string;
      scopes?: string[];
    };
    CreatePersonalAccessTokenResponse: {
      token: components["schemas"]["PersonalAccessToken"];
      value: string;
    };
    /** @enum {string} */
    ProjectStatus: "planned" | "started" | "paused" | "completed" | "canceled";
    /** @enum {string} */
    ProjectPriority: "none" | "urgent" | "high" | "medium" | "low";
    ProjectTeam: {
      /** Format: uuid */
      id: string;
      key: string;
      name: string;
    };
    ProjectProgress: {
      total: number;
      completed: number;
      percentage: number;
    };
    Project: {
      /** Format: uuid */
      id: string;
      name: string;
      description?: string | null;
      icon?: string | null;
      slug: string;
      status: components["schemas"]["ProjectStatus"];
      priority: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: uuid */
      workspace_id: string;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
      /** Format: date-time */
      canceled_at?: string | null;
      teams: components["schemas"]["ProjectTeam"][];
      progress: components["schemas"]["ProjectProgress"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    ProjectListResponse: {
      projects: components["schemas"]["Project"][];
    };
    CreateProjectRequest: {
      name: string;
      description?: string | null;
      icon?: string | null;
      slug?: string;
      status?: components["schemas"]["ProjectStatus"];
      priority?: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      team_ids?: string[];
      team_keys?: string[];
    };
    UpdateProjectRequest: {
      name?: string;
      description?: string | null;
      icon?: string | null;
      slug?: string;
      status?: components["schemas"]["ProjectStatus"];
      priority?: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      team_ids?: string[];
      team_keys?: string[];
    };
    Team: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      icon?: string | null;
      isPrivate: boolean;
      issueCount: number;
      memberCount: number;
      currentUserIsMember: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      retiredAt?: string | null;
    };
    TeamListResponse: {
      /** Format: uuid */
      workspaceId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canManageTeams: boolean;
      teams: components["schemas"]["Team"][];
    };
    CreateTeamRequest: {
      name: string;
      key?: string;
      isPrivate?: boolean;
      icon?: string;
    };
    CreateTeamResponse: {
      team: components["schemas"]["Team"];
    };
    Cycle: {
      /** Format: uuid */
      id: string;
      name?: string | null;
      number: number;
      /** Format: uuid */
      team_id: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      auto_rollover: boolean;
      issue_count: number;
      completed_issue_count: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CycleTeam: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      cyclesEnabled: boolean;
      cycleStartDay?: number | null;
      cycleDurationWeeks?: number | null;
      timezone: string;
    };
    TeamCyclesResponse: {
      team: components["schemas"]["CycleTeam"];
      cycles: components["schemas"]["Cycle"][];
    };
    CreateCycleRequest: {
      name?: string | null;
      start_date: string;
      end_date: string;
      auto_rollover?: boolean;
    };
    UpdateCycleRequest: {
      name?: string | null;
      start_date?: string;
      end_date?: string;
      auto_rollover?: boolean;
    };
    /** @enum {string} */
    WorkspaceRole: "owner" | "admin" | "member" | "guest";
    WorkspaceMembership: {
      /** Format: uuid */
      workspaceId: string;
      role: components["schemas"]["WorkspaceRole"];
      workspaceName: string;
      workspaceSlug: string;
    };
    Workspace: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      logo?: string | null;
      region: string;
      fiscalMonth: string;
      welcomeMessage: string;
      plan: string;
    };
    WorkspaceSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TeamSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      /** Format: uuid */
      workspaceId: string;
    };
    CreateWorkspaceRequest: {
      name: string;
      urlSlug: string;
    };
    CreateWorkspaceResponse: {
      workspace: components["schemas"]["WorkspaceSummary"];
      team: components["schemas"]["TeamSummary"];
    };
    CurrentWorkspaceResponse: {
      workspace: components["schemas"]["Workspace"];
    };
    UpdateWorkspaceRequest: {
      name?: string;
      urlSlug?: string;
      logo?: string | null;
      fiscalMonth?: string;
      welcomeMessage?: string;
    };
    WorkspaceMember: {
      id: string;
      /** @enum {string} */
      kind: "member" | "invitation";
      userId?: string | null;
      name: string;
      email: string;
      image?: string | null;
      role: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      status: "active" | "pending";
      teams: string[];
      /** Format: date-time */
      joinedAt: string;
      /** Format: date-time */
      lastSeenAt?: string | null;
      pronouns?: string;
      title?: string;
      location?: string;
      timezone?: string;
      showLocalTime?: boolean;
    };
    WorkspaceMembersResponse: {
      /** Format: uuid */
      workspaceId: string;
      currentUserId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canInviteMembers: boolean;
      members: components["schemas"]["WorkspaceMember"][];
    };
    MutateWorkspaceMemberRequest: {
      /** @enum {string} */
      kind: "member" | "invitation";
      id: string;
      role?: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      action?: "resend";
    };
    InviteWorkspaceMembersRequest: {
      /** Format: uuid */
      workspaceId?: string;
      invites: {
        /** Format: email */
        email: string;
        /** @enum {string} */
        role: "admin" | "member" | "guest";
      }[];
    };
    InviteResult: {
      email: string;
      /** @enum {string} */
      status: "sent" | "failed";
      error?: string;
    };
    InviteWorkspaceMembersResponse: {
      results: components["schemas"]["InviteResult"][];
    };
    SuccessResponse: {
      success: boolean;
    };
    /** @enum {string} */
    IssuePriority: "none" | "urgent" | "high" | "medium" | "low";
    Issue: {
      /** Format: uuid */
      id: string;
      number: number;
      identifier: string;
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id: string;
      assignee_id?: string | null;
      creator_id: string;
      priority: components["schemas"]["IssuePriority"];
      estimate?: number | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: date-time */
      due_date?: string | null;
      sort_order?: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      archived_at?: string | null;
      /** Format: date-time */
      canceled_at?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
    };
    IssueListResponse: {
      data: components["schemas"]["Issue"][];
      next_cursor?: string | null;
    };
    CreateIssueRequest: {
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id?: string | null;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
    };
    UpdateIssueRequest: {
      title?: string;
      description?: string | null;
      /** Format: uuid */
      state_id?: string;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
      sort_order?: number;
      archive?: boolean;
    };
  };
  responses: {
    /** @description RFC 7807 problem response */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    Cursor: string;
    Limit: number;
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listIssues: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        team_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issues page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIssueRequest"];
      };
    };
    responses: {
      /** @description Created issue */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIssueRequest"];
      };
    };
    responses: {
      /** @description Updated issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssueComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description Created comment */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  toggleIssueReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Issue reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssueReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Issue reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommentRequest"];
      };
    };
    responses: {
      /** @description Updated comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  toggleCommentReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Comment reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listLabels: {
    parameters: {
      query?: {
        scope?: "workspace" | "team" | "all";
        teamId?: string;
        includeArchived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Labels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createLabel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLabelRequest"];
      };
    };
    responses: {
      /** @description Created label */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateLabelRequest"];
      };
    };
    responses: {
      /** @description Updated label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjectLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project labels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectLabelRequest"];
      };
    };
    responses: {
      /** @description Created project label */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted project label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectLabelRequest"];
      };
    };
    responses: {
      /** @description Updated project label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listPersonalAccessTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Personal access tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalAccessTokenListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createPersonalAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePersonalAccessTokenRequest"];
      };
    };
    responses: {
      /** @description Created personal access token */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePersonalAccessTokenResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  revokePersonalAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectRequest"];
      };
    };
    responses: {
      /** @description Created project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectRequest"];
      };
    };
    responses: {
      /** @description Updated project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listTeams: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Teams */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createTeam: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamRequest"];
      };
    };
    responses: {
      /** @description Created team */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTeamResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listTeamCycles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team cycles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamCyclesResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCycleRequest"];
      };
    };
    responses: {
      /** @description Created cycle */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cycle"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted cycle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCycleRequest"];
      };
    };
    responses: {
      /** @description Updated cycle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cycle"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace memberships */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembership"][];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Created workspace */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            redirectTo: string;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Updated current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active members and pending invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  resendWorkspaceInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Resent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  removeWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  inviteWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteWorkspaceMembersRequest"];
      };
    };
    responses: {
      /** @description Invite results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteWorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  watchSync: {
    parameters: {
      query?: {
        version?: number;
        /** @description Browser/CLI WebSocket auth fallback when Authorization headers are unavailable. */
        access_token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol switch */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
}
