/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/issues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List issues in the authenticated workspace */
    get: operations["listIssues"];
    put?: never;
    /** Create an issue */
    post: operations["createIssue"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: operations["getIssue"];
    put?: never;
    post?: never;
    delete: operations["deleteIssue"];
    options?: never;
    head?: never;
    patch: operations["updateIssue"];
    trace?: never;
  };
  "/issues/{id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createIssueComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}/reactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["toggleIssueReaction"];
    delete: operations["deleteIssueReaction"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["searchIssues"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issues/{id}/subscription": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get: operations["getIssueSubscription"];
    put?: never;
    post: operations["subscribeToIssue"];
    delete: operations["unsubscribeFromIssue"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issue-templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listIssueTemplates"];
    put?: never;
    post: operations["createIssueTemplate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/issue-templates/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteIssueTemplate"];
    options?: never;
    head?: never;
    patch: operations["updateIssueTemplate"];
    trace?: never;
  };
  "/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Account route namespace; concrete resources are under /account/profile and /account/preferences. */
    get: operations["accountNamespace"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/account/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAccountProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateAccountProfile"];
    trace?: never;
  };
  "/account/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAccountPreferences"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateAccountPreferences"];
    trace?: never;
  };
  "/comments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    patch: operations["updateComment"];
    trace?: never;
  };
  "/comments/{id}/reactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["toggleCommentReaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/custom-emojis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCustomEmojis"];
    put?: never;
    post: operations["createCustomEmoji"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/custom-emojis/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteCustomEmoji"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/document-settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getDocumentSettings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/document-folders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createDocumentFolder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/document-folders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteDocumentFolder"];
    options?: never;
    head?: never;
    patch: operations["updateDocumentFolder"];
    trace?: never;
  };
  "/document-templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createDocumentTemplate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/document-templates/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteDocumentTemplate"];
    options?: never;
    head?: never;
    patch: operations["updateDocumentTemplate"];
    trace?: never;
  };
  "/integrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listIntegrations"];
    put?: never;
    post?: never;
    delete: operations["deleteIntegration"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listLabels"];
    put?: never;
    post: operations["createLabel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/labels/bulk": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["bulkLabelAction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/labels/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteLabel"];
    options?: never;
    head?: never;
    patch: operations["updateLabel"];
    trace?: never;
  };
  "/project-labels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listProjectLabels"];
    put?: never;
    post: operations["createProjectLabel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project-labels/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteProjectLabel"];
    options?: never;
    head?: never;
    patch: operations["updateProjectLabel"];
    trace?: never;
  };
  "/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listNotifications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications/bulk-read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["markNotificationsRead"];
    trace?: never;
  };
  "/notifications/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["markNotificationRead"];
    trace?: never;
  };
  "/notifications/{id}/unread": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["markNotificationUnread"];
    trace?: never;
  };
  "/notifications/{id}/snooze": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["snoozeNotification"];
    trace?: never;
  };
  "/personal-access-tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPersonalAccessTokens"];
    put?: never;
    post: operations["createPersonalAccessToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/personal-access-tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["revokePersonalAccessToken"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project-templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List project templates in the authenticated workspace */
    get: operations["listProjectTemplates"];
    put?: never;
    /** Create a project template */
    post: operations["createProjectTemplate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/project-templates/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteProjectTemplate"];
    options?: never;
    head?: never;
    patch: operations["updateProjectTemplate"];
    trace?: never;
  };
  "/project-statuses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List configurable project statuses for the authenticated workspace */
    get: operations["listProjectStatuses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Replace configurable project statuses for the authenticated workspace */
    patch: operations["updateProjectStatuses"];
    trace?: never;
  };
  "/sidebar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sidebar route namespace; concrete resources are under /sidebar/favorites. */
    get: operations["sidebarNamespace"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sidebar/favorites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listSidebarFavorites"];
    put?: never;
    post: operations["addSidebarFavorite"];
    delete: operations["removeSidebarFavorite"];
    options?: never;
    head?: never;
    patch: operations["reorderSidebarFavorites"];
    trace?: never;
  };
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects in the authenticated workspace */
    get: operations["listProjects"];
    put?: never;
    /** Create a project */
    post: operations["createProject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    get: operations["getProject"];
    put?: never;
    post?: never;
    delete: operations["deleteProject"];
    options?: never;
    head?: never;
    patch: operations["updateProject"];
    trace?: never;
  };
  "/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List visible teams in the authenticated workspace */
    get: operations["listTeams"];
    put?: never;
    /** Create a team with default workflow states */
    post: operations["createTeam"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/teams/{key}/cycles": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    get: operations["listTeamCycles"];
    put?: never;
    post: operations["createTeamCycle"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/teams/{key}/create-issue-options": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    get: operations["getTeamCreateIssueOptions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/teams/{key}/cycles/{cycle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteTeamCycle"];
    options?: never;
    head?: never;
    patch: operations["updateTeamCycle"];
    trace?: never;
  };
  "/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspaces for the authenticated principal */
    get: operations["listWorkspaces"];
    put?: never;
    /** Create a workspace with a default team and workflow states */
    post: operations["createWorkspace"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/workspaces/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCurrentWorkspace"];
    put?: never;
    post?: never;
    delete: operations["deleteCurrentWorkspace"];
    options?: never;
    head?: never;
    patch: operations["updateCurrentWorkspace"];
    trace?: never;
  };
  "/workspaces/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listWorkspaceMembers"];
    put?: never;
    post: operations["resendWorkspaceInvitation"];
    delete: operations["removeWorkspaceMemberOrInvitation"];
    options?: never;
    head?: never;
    patch: operations["updateWorkspaceMemberOrInvitation"];
    trace?: never;
  };
  "/workspaces/invite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["inviteWorkspaceMembers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sync/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open a workspace sync WebSocket and replay operations after a version */
    get: operations["watchSync"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      detail?: string;
    };
    AccountProfile: {
      name: string;
      email: string;
      username: string;
      pronouns: string;
      title: string;
      location: string;
      timezone: string;
      showLocalTime: boolean;
      image?: string | null;
    };
    WorkspaceAccess: {
      /** Format: uuid */
      currentWorkspaceId?: string | null;
      currentWorkspaceName?: string | null;
    };
    AccountProfileResponse: {
      profile: components["schemas"]["AccountProfile"];
      workspaceAccess: components["schemas"]["WorkspaceAccess"];
    };
    UpdateAccountProfileRequest: {
      name: string;
      username?: string;
      image?: string | null;
      pronouns?: string;
      title?: string;
      location?: string;
      timezone?: string;
      showLocalTime?: boolean;
    };
    AccountPreferencesResponse: {
      accountPreferences: {
        [key: string]: unknown;
      };
    };
    UpdateAccountPreferencesRequest: {
      accountPreferences: {
        [key: string]: unknown;
      };
    };
    CommentUser: {
      name: string;
      image?: string | null;
    };
    ReactionSummary: {
      emoji: string;
      count: number;
      reacted?: boolean;
      reactedByMe?: boolean;
    };
    ReactionSummaryList: components["schemas"]["ReactionSummary"][];
    Comment: {
      /** Format: uuid */
      id: string;
      body: string;
      /** Format: uuid */
      issue_id: string;
      user_id: string;
      user: components["schemas"]["CommentUser"];
      owned_by_me: boolean;
      can_edit: boolean;
      can_delete: boolean;
      reactions: components["schemas"]["ReactionSummary"][];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateCommentRequest: {
      body: string;
    };
    UpdateCommentRequest: {
      body: string;
    };
    ReactionRequest: {
      emoji: string;
    };
    CustomEmoji: {
      id: string;
      name: string;
      imageUrl: string;
      /** Format: date-time */
      createdAt: string;
    };
    CustomEmojiListResponse: {
      emojis: components["schemas"]["CustomEmoji"][];
    };
    CustomEmojiResponse: {
      emoji: components["schemas"]["CustomEmoji"];
    };
    CreateCustomEmojiRequest: {
      name: string;
      imageUrl: string;
    };
    DocumentTemplate: {
      id: string;
      name: string;
      description: string;
      content: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DocumentFolder: {
      id: string;
      name: string;
      description: string;
      /** @enum {string} */
      color:
        | "gray"
        | "blue"
        | "green"
        | "yellow"
        | "orange"
        | "purple"
        | "pink";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DocumentSettings: {
      templates: components["schemas"]["DocumentTemplate"][];
      folders: components["schemas"]["DocumentFolder"][];
    };
    DocumentSettingsResponse: {
      documents: components["schemas"]["DocumentSettings"];
    };
    DocumentFolderResponse: {
      folder: components["schemas"]["DocumentFolder"];
    };
    DocumentTemplateResponse: {
      template: components["schemas"]["DocumentTemplate"];
    };
    DocumentFolderRequest: {
      name?: string;
      description?: string;
      /** @enum {string} */
      color?:
        | "gray"
        | "blue"
        | "green"
        | "yellow"
        | "orange"
        | "purple"
        | "pink";
    };
    DocumentTemplateRequest: {
      name?: string;
      description?: string;
      content?: string;
    };
    IntegrationSetupRequirement: {
      type: string;
      message: string;
    };
    IntegrationActions: {
      canConnect: boolean;
      canManage: boolean;
      canDisconnect: boolean;
    };
    Integration: {
      /** @enum {string} */
      provider: "github" | "slack" | "zendesk";
      name: string;
      description: string;
      /** Format: uuid */
      id: string | null;
      status: string;
      displayName: string | null;
      externalId: string | null;
      /** Format: date-time */
      connectedAt: string | null;
      setupRequirement:
        | components["schemas"]["IntegrationSetupRequirement"]
        | null;
      actions: components["schemas"]["IntegrationActions"];
    };
    IntegrationListResponse: {
      canManageIntegrations: boolean;
      integrations: components["schemas"]["Integration"][];
    };
    Label: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
      teamName?: string | null;
      teamKey?: string | null;
      /** @enum {string} */
      scope: "workspace" | "team";
      /** Format: date-time */
      archivedAt?: string | null;
      issueCount: number;
      /** Format: date-time */
      lastApplied?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LabelListResponse: {
      labels: components["schemas"]["Label"][];
    };
    LabelResponse: {
      label: components["schemas"]["Label"];
    };
    CreateLabelRequest: {
      name: string;
      color?: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
    };
    UpdateLabelRequest: {
      name?: string;
      color?: string;
      description?: string | null;
      /** Format: uuid */
      parentLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
      archived?: boolean;
      convertToGroup?: boolean;
    };
    BulkLabelRequest: {
      /** @enum {string} */
      action:
        | "archive"
        | "unarchive"
        | "delete"
        | "convertToGroup"
        | "rescope"
        | "merge";
      labelIds: string[];
      /** Format: uuid */
      destinationLabelId?: string | null;
      /** Format: uuid */
      teamId?: string | null;
    };
    BulkLabelResponse: {
      success: boolean;
      updatedCount?: number;
      /** Format: uuid */
      destinationLabelId?: string | null;
      mergedCount?: number;
    };
    ProjectLabel: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
      description?: string | null;
      projectCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ProjectLabelListResponse: {
      labels: components["schemas"]["ProjectLabel"][];
    };
    ProjectLabelResponse: {
      label: components["schemas"]["ProjectLabel"];
    };
    CreateProjectLabelRequest: {
      name: string;
      color?: string;
      description?: string | null;
    };
    UpdateProjectLabelRequest: {
      name?: string;
      color?: string;
      description?: string | null;
    };
    Notification: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      type:
        | "assigned"
        | "mentioned"
        | "status_change"
        | "comment"
        | "duplicate";
      actorName: string;
      actorImage?: string | null;
      issueIdentifier: string;
      issueTitle: string;
      issuePriority: string;
      /** Format: uuid */
      issueId?: string | null;
      /** Format: date-time */
      readAt?: string | null;
      /** Format: date-time */
      snoozedUntilAt?: string | null;
      /** Format: date-time */
      unsnoozedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    NotificationListResponse: {
      notifications: components["schemas"]["Notification"][];
      unreadCount: number;
    };
    BulkReadNotificationsResponse: {
      success: boolean;
      updatedCount: number;
      unreadCount: number;
    };
    NotificationSnoozeInfo: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      snoozedUntilAt: string | null;
      /** Format: date-time */
      unsnoozedAt: string | null;
    };
    NotificationActionResponse: {
      success: boolean;
      unreadCount: number;
      notification?: components["schemas"]["NotificationSnoozeInfo"] | null;
    };
    SnoozeNotificationRequest: {
      /** Format: date-time */
      snoozedUntilAt?: string | null;
    };
    PersonalAccessToken: {
      /** Format: uuid */
      id: string;
      name: string;
      token_prefix: string;
      scopes: string[];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      last_used_at?: string | null;
      /** Format: date-time */
      revoked_at?: string | null;
    };
    PersonalAccessTokenListResponse: {
      tokens: components["schemas"]["PersonalAccessToken"][];
    };
    CreatePersonalAccessTokenRequest: {
      name: string;
      scopes?: string[];
    };
    CreatePersonalAccessTokenResponse: {
      token: components["schemas"]["PersonalAccessToken"];
      value: string;
    };
    ProjectTemplateSettings: {
      /** @enum {string|null} */
      status:
        | "planned"
        | "started"
        | "paused"
        | "completed"
        | "canceled"
        | null;
      /** @enum {string|null} */
      priority: "none" | "urgent" | "high" | "medium" | "low" | null;
      labelIds: string[];
      milestones: string[];
    };
    ProjectTemplate: {
      /** Format: uuid */
      id: string;
      name: string;
      description: string;
      settings: components["schemas"]["ProjectTemplateSettings"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ProjectTemplateListResponse: {
      templates: components["schemas"]["ProjectTemplate"][];
    };
    ProjectTemplateResponse: {
      template: components["schemas"]["ProjectTemplate"];
    };
    ProjectTemplateRequest: {
      name: string;
      description?: string | null;
      settings?: components["schemas"]["ProjectTemplateSettings"];
    };
    ProjectStatusConfig: {
      id: string;
      key: string;
      name: string;
      description: string;
      color: string;
      icon: string;
      position: number;
      isDefault: boolean;
      projectCount: number;
    };
    ProjectStatusListResponse: {
      statuses: components["schemas"]["ProjectStatusConfig"][];
      totalProjects: number;
      readOnly: boolean;
      customStatusesSupported: boolean;
      canManage: boolean;
    };
    UpdateProjectStatusesRequest: {
      statuses: components["schemas"]["ProjectStatusConfig"][];
    };
    /** @enum {string} */
    SidebarFavoriteObjectType: "project" | "issue" | "view";
    SidebarFavorite: {
      id: string;
      objectType: components["schemas"]["SidebarFavoriteObjectType"];
      objectId: string;
      /** Format: date-time */
      createdAt: string;
      label: string;
      href: string;
      context: string | null;
    };
    SidebarFavoriteListResponse: {
      favorites: components["schemas"]["SidebarFavorite"][];
    };
    SidebarFavoriteRequest: {
      objectType: components["schemas"]["SidebarFavoriteObjectType"];
      objectId: string;
    };
    ReorderSidebarFavoritesRequest: {
      orderedIds: string[];
    };
    /** @enum {string} */
    ProjectStatus: "planned" | "started" | "paused" | "completed" | "canceled";
    /** @enum {string} */
    ProjectPriority: "none" | "urgent" | "high" | "medium" | "low";
    ProjectTeam: {
      /** Format: uuid */
      id: string;
      key: string;
      name: string;
    };
    ProjectProgress: {
      total: number;
      completed: number;
      percentage: number;
    };
    Project: {
      /** Format: uuid */
      id: string;
      name: string;
      description?: string | null;
      icon?: string | null;
      slug: string;
      status: components["schemas"]["ProjectStatus"];
      priority: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: uuid */
      workspace_id: string;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
      /** Format: date-time */
      canceled_at?: string | null;
      teams: components["schemas"]["ProjectTeam"][];
      progress: components["schemas"]["ProjectProgress"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    ProjectListResponse: {
      projects: components["schemas"]["Project"][];
    };
    CreateProjectRequest: {
      name: string;
      description?: string | null;
      icon?: string | null;
      slug?: string;
      status?: components["schemas"]["ProjectStatus"];
      priority?: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      team_ids?: string[];
      team_keys?: string[];
    };
    UpdateProjectRequest: {
      name?: string;
      description?: string | null;
      icon?: string | null;
      slug?: string;
      status?: components["schemas"]["ProjectStatus"];
      priority?: components["schemas"]["ProjectPriority"];
      lead_id?: string | null;
      /** Format: date-time */
      start_date?: string | null;
      /** Format: date-time */
      target_date?: string | null;
      team_ids?: string[];
      team_keys?: string[];
    };
    Team: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      icon?: string | null;
      isPrivate: boolean;
      issueCount: number;
      memberCount: number;
      currentUserIsMember: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      retiredAt?: string | null;
    };
    TeamListResponse: {
      /** Format: uuid */
      workspaceId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canManageTeams: boolean;
      teams: components["schemas"]["Team"][];
    };
    CreateTeamRequest: {
      name: string;
      key?: string;
      isPrivate?: boolean;
      icon?: string;
    };
    CreateTeamResponse: {
      team: components["schemas"]["Team"];
    };
    CreateIssueOptionsTeam: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      cyclesEnabled: boolean;
      estimateType: string;
    };
    CreateIssueOptionStatus: {
      /** Format: uuid */
      id: string;
      name: string;
      category: string;
      color: string;
      isDefault: boolean | null;
      behavior: {
        [key: string]: unknown;
      };
    };
    CreateIssueOptionUser: {
      id: string;
      name: string;
      image: string | null;
    };
    CreateIssueOptionLabel: {
      /** Format: uuid */
      id: string;
      name: string;
      color: string;
    };
    CreateIssueOptionProject: {
      /** Format: uuid */
      id: string;
      name: string;
      icon: string | null;
    };
    CreateIssueOptionCycle: {
      /** Format: uuid */
      id: string;
      name: string;
      number: number;
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string;
    };
    CreateIssueOptionTemplate: {
      /** Format: uuid */
      id: string;
      name: string;
      description: string;
      settings: {
        [key: string]: unknown;
      };
    };
    CreateIssueOptionRelationIssue: {
      /** Format: uuid */
      id: string;
      identifier: string;
      title: string;
    };
    NumberOption: {
      value: number;
      label: string;
    };
    StringOption: {
      value: string;
      label: string;
    };
    CreateIssueOptionsResponse: {
      team: components["schemas"]["CreateIssueOptionsTeam"];
      statuses: components["schemas"]["CreateIssueOptionStatus"][];
      priorities: components["schemas"]["StringOption"][];
      assignees: components["schemas"]["CreateIssueOptionUser"][];
      labels: components["schemas"]["CreateIssueOptionLabel"][];
      projects: components["schemas"]["CreateIssueOptionProject"][];
      cycles: components["schemas"]["CreateIssueOptionCycle"][];
      estimates: components["schemas"]["NumberOption"][];
      templates: components["schemas"]["CreateIssueOptionTemplate"][];
      relationIssues: components["schemas"]["CreateIssueOptionRelationIssue"][];
      dueDatePresets: components["schemas"]["StringOption"][];
    };
    Cycle: {
      /** Format: uuid */
      id: string;
      name?: string | null;
      number: number;
      /** Format: uuid */
      team_id: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      auto_rollover: boolean;
      issue_count: number;
      completed_issue_count: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CycleTeam: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      cyclesEnabled: boolean;
      cycleStartDay?: number | null;
      cycleDurationWeeks?: number | null;
      timezone: string;
    };
    TeamCyclesResponse: {
      team: components["schemas"]["CycleTeam"];
      cycles: components["schemas"]["Cycle"][];
    };
    CreateCycleRequest: {
      name?: string | null;
      start_date: string;
      end_date: string;
      auto_rollover?: boolean;
    };
    UpdateCycleRequest: {
      name?: string | null;
      start_date?: string;
      end_date?: string;
      auto_rollover?: boolean;
    };
    /** @enum {string} */
    WorkspaceRole: "owner" | "admin" | "member" | "guest";
    WorkspaceMembership: {
      /** Format: uuid */
      workspaceId: string;
      role: components["schemas"]["WorkspaceRole"];
      workspaceName: string;
      workspaceSlug: string;
    };
    Workspace: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      logo?: string | null;
      region: string;
      fiscalMonth: string;
      welcomeMessage: string;
      plan: string;
    };
    WorkspaceSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      urlSlug: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    TeamSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      key: string;
      /** Format: uuid */
      workspaceId: string;
    };
    CreateWorkspaceRequest: {
      name: string;
      urlSlug: string;
    };
    CreateWorkspaceResponse: {
      workspace: components["schemas"]["WorkspaceSummary"];
      team: components["schemas"]["TeamSummary"];
    };
    CurrentWorkspaceResponse: {
      workspace: components["schemas"]["Workspace"];
    };
    UpdateWorkspaceRequest: {
      name?: string;
      urlSlug?: string;
      logo?: string | null;
      fiscalMonth?: string;
      welcomeMessage?: string;
    };
    WorkspaceMember: {
      id: string;
      /** @enum {string} */
      kind: "member" | "invitation";
      userId?: string | null;
      name: string;
      email: string;
      image?: string | null;
      role: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      status: "active" | "pending";
      teams: string[];
      /** Format: date-time */
      joinedAt: string;
      /** Format: date-time */
      lastSeenAt?: string | null;
      pronouns?: string;
      title?: string;
      location?: string;
      timezone?: string;
      showLocalTime?: boolean;
    };
    WorkspaceMembersResponse: {
      /** Format: uuid */
      workspaceId: string;
      currentUserId: string;
      viewerRole: components["schemas"]["WorkspaceRole"];
      canInviteMembers: boolean;
      members: components["schemas"]["WorkspaceMember"][];
    };
    MutateWorkspaceMemberRequest: {
      /** @enum {string} */
      kind: "member" | "invitation";
      id: string;
      role?: components["schemas"]["WorkspaceRole"];
      /** @enum {string} */
      action?: "resend";
    };
    InviteWorkspaceMembersRequest: {
      /** Format: uuid */
      workspaceId?: string;
      invites: {
        /** Format: email */
        email: string;
        /** @enum {string} */
        role: "admin" | "member" | "guest";
      }[];
    };
    InviteResult: {
      email: string;
      /** @enum {string} */
      status: "sent" | "failed";
      error?: string;
    };
    InviteWorkspaceMembersResponse: {
      results: components["schemas"]["InviteResult"][];
    };
    SuccessResponse: {
      success: boolean;
    };
    /** @enum {string} */
    IssuePriority: "none" | "urgent" | "high" | "medium" | "low";
    Issue: {
      /** Format: uuid */
      id: string;
      number: number;
      identifier: string;
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id: string;
      assignee_id?: string | null;
      creator_id: string;
      priority: components["schemas"]["IssuePriority"];
      estimate?: number | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: date-time */
      due_date?: string | null;
      sort_order?: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      archived_at?: string | null;
      /** Format: date-time */
      canceled_at?: string | null;
      /** Format: date-time */
      completed_at?: string | null;
    };
    IssueListResponse: {
      data: components["schemas"]["Issue"][];
      next_cursor?: string | null;
    };
    IssueTemplateSettings: {
      title?: string;
      body?: string;
      /** @enum {string} */
      defaultPriority?: "urgent" | "high" | "medium" | "low" | "none";
      defaultStatusId?: string;
      defaultStatusName?: string;
      defaultTeamId?: string;
      defaultTeamKey?: string;
      defaultScope?: string;
      defaultProjectId?: string | null;
      archivedAt?: string;
    };
    IssueTemplate: {
      /** Format: uuid */
      id: string;
      name: string;
      description: string;
      type: string;
      /** Format: uuid */
      teamId: string | null;
      settings: components["schemas"]["IssueTemplateSettings"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    IssueTemplateListResponse: {
      templates: components["schemas"]["IssueTemplate"][];
    };
    IssueTemplateResponse: {
      template: components["schemas"]["IssueTemplate"];
    };
    CreateIssueTemplateRequest: {
      name?: string;
      description?: string;
      settings?: components["schemas"]["IssueTemplateSettings"];
      /** Format: uuid */
      duplicateFromId?: string;
    };
    UpdateIssueTemplateRequest: {
      name?: string;
      description?: string;
      settings?: components["schemas"]["IssueTemplateSettings"];
      archived?: boolean;
    };
    IssueSearchResult: {
      /** Format: uuid */
      id: string;
      identifier: string;
      title: string;
      priority: components["schemas"]["IssuePriority"];
      stateName: string;
      stateCategory: string;
      stateColor: string;
      assigneeName: string | null;
      assigneeImage: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    IssueSubscriptionSummary: {
      subscribed: boolean;
      watcherCount: number;
    };
    CreateIssueRequest: {
      title: string;
      description?: string | null;
      /** Format: uuid */
      team_id: string;
      /** Format: uuid */
      state_id?: string | null;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
    };
    UpdateIssueRequest: {
      title?: string;
      description?: string | null;
      /** Format: uuid */
      state_id?: string;
      priority?: components["schemas"]["IssuePriority"];
      assignee_id?: string | null;
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      project_milestone_id?: string | null;
      /** Format: uuid */
      cycle_id?: string | null;
      /** Format: uuid */
      parent_issue_id?: string | null;
      estimate?: number | null;
      /** Format: date */
      due_date?: string | null;
      sort_order?: number;
      archive?: boolean;
    };
  };
  responses: {
    /** @description RFC 7807 problem response */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    Cursor: string;
    Limit: number;
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listIssues: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
        team_id?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issues page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIssueRequest"];
      };
    };
    responses: {
      /** @description Created issue */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateIssue: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIssueRequest"];
      };
    };
    responses: {
      /** @description Updated issue */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Issue"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssueComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description Created comment */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  toggleIssueReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Issue reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssueReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Issue reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  searchIssues: {
    parameters: {
      query?: {
        q?: string;
        workspaceId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue search results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueSearchResult"][];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getIssueSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue subscription summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueSubscriptionSummary"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  subscribeToIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue subscription summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueSubscriptionSummary"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  unsubscribeFromIssue: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue subscription summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueSubscriptionSummary"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listIssueTemplates: {
    parameters: {
      query?: {
        teamKey?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Issue templates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueTemplateListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createIssueTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIssueTemplateRequest"];
      };
    };
    responses: {
      /** @description Created issue template */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIssueTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted issue template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateIssueTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIssueTemplateRequest"];
      };
    };
    responses: {
      /** @description Updated issue template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IssueTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  accountNamespace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: components["responses"]["Problem"];
    };
  };
  getAccountProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountProfileResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateAccountProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountProfileRequest"];
      };
    };
    responses: {
      /** @description Updated account profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountProfileResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getAccountPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account preferences */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountPreferencesResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateAccountPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountPreferencesRequest"];
      };
    };
    responses: {
      /** @description Updated account preferences */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountPreferencesResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommentRequest"];
      };
    };
    responses: {
      /** @description Updated comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  toggleCommentReaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactionRequest"];
      };
    };
    responses: {
      /** @description Comment reaction summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReactionSummaryList"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listCustomEmojis: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Custom emojis */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomEmojiListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createCustomEmoji: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCustomEmojiRequest"];
      };
    };
    responses: {
      /** @description Created custom emoji */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomEmojiResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCustomEmoji: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted custom emoji */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            ok: boolean;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getDocumentSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentSettingsResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createDocumentFolder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentFolderRequest"];
      };
    };
    responses: {
      /** @description Created document folder */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentFolderResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteDocumentFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted document folder */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateDocumentFolder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentFolderRequest"];
      };
    };
    responses: {
      /** @description Updated document folder */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentFolderResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createDocumentTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentTemplateRequest"];
      };
    };
    responses: {
      /** @description Created document template */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteDocumentTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted document template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateDocumentTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentTemplateRequest"];
      };
    };
    responses: {
      /** @description Updated document template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listIntegrations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace integrations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IntegrationListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteIntegration: {
    parameters: {
      query: {
        provider: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted integration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listLabels: {
    parameters: {
      query?: {
        scope?: "workspace" | "team" | "all";
        teamId?: string;
        includeArchived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Labels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createLabel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateLabelRequest"];
      };
    };
    responses: {
      /** @description Created label */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  bulkLabelAction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkLabelRequest"];
      };
    };
    responses: {
      /** @description Bulk label action result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkLabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateLabelRequest"];
      };
    };
    responses: {
      /** @description Updated label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjectLabels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project labels */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectLabelRequest"];
      };
    };
    responses: {
      /** @description Created project label */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted project label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProjectLabel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectLabelRequest"];
      };
    };
    responses: {
      /** @description Updated project label */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectLabelResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  markNotificationsRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bulk mark notifications read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkReadNotificationsResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  markNotificationRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification read result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationActionResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  markNotificationUnread: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification unread result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationActionResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  snoozeNotification: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SnoozeNotificationRequest"];
      };
    };
    responses: {
      /** @description Notification snooze result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationActionResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listPersonalAccessTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Personal access tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalAccessTokenListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createPersonalAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePersonalAccessTokenRequest"];
      };
    };
    responses: {
      /** @description Created personal access token */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreatePersonalAccessTokenResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  revokePersonalAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjectTemplates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project templates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectTemplateListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createProjectTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectTemplateRequest"];
      };
    };
    responses: {
      /** @description Created project template */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteProjectTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted project template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProjectTemplate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectTemplateRequest"];
      };
    };
    responses: {
      /** @description Updated project template */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectTemplateResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjectStatuses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project statuses */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectStatusListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProjectStatuses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectStatusesRequest"];
      };
    };
    responses: {
      /** @description Updated project statuses */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectStatusListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  sidebarNamespace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: components["responses"]["Problem"];
    };
  };
  listSidebarFavorites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sidebar favorites */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SidebarFavoriteListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  addSidebarFavorite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SidebarFavoriteRequest"];
      };
    };
    responses: {
      /** @description Sidebar favorites */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SidebarFavoriteListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  removeSidebarFavorite: {
    parameters: {
      query: {
        objectType: components["schemas"]["SidebarFavoriteObjectType"];
        objectId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sidebar favorites */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SidebarFavoriteListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  reorderSidebarFavorites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderSidebarFavoritesRequest"];
      };
    };
    responses: {
      /** @description Sidebar favorites */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SidebarFavoriteListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectRequest"];
      };
    };
    responses: {
      /** @description Created project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectRequest"];
      };
    };
    responses: {
      /** @description Updated project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listTeams: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Teams */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamListResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createTeam: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTeamRequest"];
      };
    };
    responses: {
      /** @description Created team */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateTeamResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listTeamCycles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team cycles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TeamCyclesResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCycleRequest"];
      };
    };
    responses: {
      /** @description Created cycle */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cycle"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getTeamCreateIssueOptions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Team create issue options */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateIssueOptionsResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted cycle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateTeamCycle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
        cycle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCycleRequest"];
      };
    };
    responses: {
      /** @description Updated cycle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cycle"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace memberships */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembership"][];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Created workspace */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            redirectTo: string;
          };
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateCurrentWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceRequest"];
      };
    };
    responses: {
      /** @description Updated current workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentWorkspaceResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Active members and pending invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  resendWorkspaceInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Resent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  removeWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateWorkspaceMemberOrInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MutateWorkspaceMemberRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  inviteWorkspaceMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteWorkspaceMembersRequest"];
      };
    };
    responses: {
      /** @description Invite results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteWorkspaceMembersResponse"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  watchSync: {
    parameters: {
      query?: {
        version?: number;
        /** @description Browser/CLI WebSocket auth fallback when Authorization headers are unavailable. */
        access_token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket protocol switch */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
}
