#!/bin/bash
# Code Quality Ralph: Detect and fix copy-paste duplication via jscpd
#
# Flow:
#   1. Run jscpd with JSON reporter
#   2. Parse JSON into a markdown checklist (cpd-checklist.md)
#   3. Loop: spawn Claude to fix one unchecked item per iteration
#   4. Re-run jscpd at the end to verify improvement
#
# Usage: ./ralph/cpd-ralph.sh [max-iterations]

set -euo pipefail
cd "$(dirname "$0")/.."

# macOS does not ship GNU timeout — use gtimeout from coreutils or provide a fallback
if ! command -v timeout &>/dev/null; then
  if command -v gtimeout &>/dev/null; then
    timeout() { gtimeout "$@"; }
  else
    timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
  fi
fi

ITERATIONS="${1:-999}"
CHECKLIST="cpd-checklist.md"
REPORT_DIR=".cpd-report"
LOG_FILE="cpd-ralph-$(date +%Y%m%d-%H%M%S).log"

log() { echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"; }

count_unchecked() { local n; n=$(grep -c '^- \[ \]' "$CHECKLIST" 2>/dev/null) || true; echo "${n:-0}"; }
count_checked()   { local n; n=$(grep -c '^- \[x\]' "$CHECKLIST" 2>/dev/null) || true; echo "${n:-0}"; }

log "=== CPD Ralph: Code Duplication Cleanup ==="
log "Max iterations: $ITERATIONS"
echo ""

# ─── Step 1: Run jscpd with JSON output ───

log "Running jscpd..."
npm run cpd -- -r json -o "$REPORT_DIR" 2>&1 || true
log "jscpd scan complete."

# ─── Step 2: Parse JSON into checklist ───

log "Generating checklist..."

node -e "
const fs = require('fs');
const report = JSON.parse(fs.readFileSync('$REPORT_DIR/jscpd-report.json', 'utf8'));
const dupes = report.duplicates || [];

// Deduplicate by file pair — keep the largest clone per pair
const pairMap = new Map();
for (const d of dupes) {
  const a = d.firstFile.name;
  const b = d.secondFile.name;
  const key = [a, b].sort().join(' <-> ');
  const existing = pairMap.get(key);
  if (!existing || d.lines > existing.lines) {
    pairMap.set(key, d);
  }
}

const unique = [...pairMap.values()];

// Preserve already-checked items from existing checklist
const checked = new Set();
if (fs.existsSync('$CHECKLIST')) {
  for (const line of fs.readFileSync('$CHECKLIST', 'utf8').split('\n')) {
    if (line.startsWith('- [x]')) {
      // Extract the file pair key from the line
      const files = [...line.matchAll(/\*\*(.+?)\*\*/g)].map(m => m[1]);
      if (files.length === 2) checked.add(files.sort().join(' <-> '));
    }
  }
}

// Generate markdown
let md = '# Code Duplication Checklist\n\n';
md += 'Generated by cpd-ralph.sh on ' + new Date().toISOString().slice(0, 10) + '\n';
md += 'Total clone groups: ' + unique.length + '\n\n';

for (const d of unique) {
  const a = d.firstFile.name;
  const b = d.secondFile.name;
  const key = [a, b].sort().join(' <-> ');
  const mark = checked.has(key) ? 'x' : ' ';
  md += '- [' + mark + '] **' + a + '** [L' + d.firstFile.start + '-' + d.firstFile.end + ']';
  md += ' <-> **' + b + '** [L' + d.secondFile.start + '-' + d.secondFile.end + ']';
  md += ' (' + d.lines + ' lines)\n';
}

fs.writeFileSync('$CHECKLIST', md);
console.log('Wrote ' + unique.length + ' items to $CHECKLIST');
"

TOTAL_ITEMS=$(count_unchecked)
log "Found $TOTAL_ITEMS unchecked items in $CHECKLIST"

if [ "$TOTAL_ITEMS" -eq 0 ]; then
  log "No duplicates to fix. Done!"
  exit 0
fi

# ─── Step 3: Fix loop ───

for ((i=1; i<=$ITERATIONS; i++)); do
  REMAINING=$(count_unchecked)
  DONE=$(count_checked)
  log "--- Iteration $i/$ITERATIONS ($DONE done, $REMAINING remaining) ---"

  if [ "$REMAINING" -eq 0 ]; then
    log "All items checked!"
    break
  fi

  result=$(timeout 600 claude -p --dangerously-skip-permissions --model claude-sonnet-4-6 \
"@ralph/cpd-prompt.md @$CHECKLIST @CLAUDE.md

ITERATION: $i of $ITERATIONS
PROGRESS: $DONE done, $REMAINING remaining

Fix exactly ONE unchecked item (the first \`- [ ]\` entry). Do NOT commit or push — just leave changes unstaged.
Output <promise>NEXT</promise> when done with this item.
Output <promise>COMPLETE</promise> only if ALL items are checked." 2>&1)

  echo "$result" | tail -5

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    log "All duplicates resolved!"
    break
  fi

  if [[ "$result" == *"<promise>NEXT</promise>"* ]]; then
    log "Item fixed. Moving to next..."
    continue
  fi

  # No promise = crash or context overflow
  log "WARNING: No promise found. Agent may have crashed. Restarting..."
  sleep 3
done

# ─── Step 4: Final verification ───

log ""
log "--- Final jscpd scan ---"
npm run cpd 2>&1 | tail -15 || true

DONE=$(count_checked)
REMAINING=$(count_unchecked)

log ""
log "========================================="
log "  CPD RALPH COMPLETE"
log "  Fixed: $DONE items"
log "  Remaining: $REMAINING items"
log "  Checklist: $CHECKLIST"
log "========================================="
